export const SET_INITIALIZE = 'SET_INITIALIZE';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_TASKS_SEARCH_KEY = 'SET_TASKS_SEARCH_KEY';
export const TOGGLE_TASKS_SORT_ORDER = 'TOGGLE_TASKS_SORT_ORDER';
